# Generated by Django 5.1.3 on 2024-11-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Назва продукту')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Пошта користувача')),
                ('description', models.TextField(verbose_name='Опис відгуку')),
                ('rating', models.IntegerField(choices=[(1, '1 - дуже погано'), (2, '2 - погано'), (3, '3 - середньо'), (4, '4 - добре'), (5, '5 - відмінно')], verbose_name='Оцінка')),
                ('review_type', models.CharField(choices=[('positive', 'Позитивний'), ('negative', 'Негативний')], max_length=10, verbose_name='Тип відгуку')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефону')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Зображення')),
            ],
        ),
    ]
