# Generated by Django 5.1.4 on 2025-01-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='description_html',
            field=models.TextField(default=1, verbose_name='Опис акції  у HTML'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='description',
            field=models.TextField(blank=True, default='No description provided.', null=True, verbose_name='Опис акції'),
        ),
    ]
