# Generated by Django 5.1.4 on 2025-01-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sale_description_html_alter_sale_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Опис акції'),
        ),
    ]
