# Generated by Django 5.1.4 on 2025-01-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_sale_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Зображення')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайди',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='sale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sales/', verbose_name='Зображення'),
        ),
    ]
